### ISSUE TITLE
outputWriterOpenTSDB not working on latest release

### ISSUE THREAD

**Issue by vfork001** [jmxtrans/jmxtrans#443]
same config works in ver 253, but not 254

[07 Apr 2016 15:44:29] [ServerScheduler_Worker-1] 163428 ERROR (com.googlecode.jmxtrans.jmx.JmxUtils:62) - Could not submit query ProcessQueryThread(log=org.slf4j.impl.Log4jLoggerAdapter(com.googlecode.jmxtrans.jmx.ProcessQueryThread), server=Server(pid=null, host=triumph08, port=8999, url=service:jmx:rmi:///jndi/rmi://triumph08:8999/jmxrmi, cronExpression=null, numQueryThreads=2), query=Query(objectName=java.lang:type=Memory, keys=[], attr=[HeapMemoryUsage, NonHeapMemoryUsage], typeNames=[], resultAlias=heap, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[BaseOutputWriter(typeNames=[], debugEnabled=false, settings={}, valueTransformer=com.googlecode.jmxtrans.model.results.IdentityValueTransformer@7baec269)])). You could try to size the 'queryProcessorExecutor' to a larger size.
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@476b0f0c rejected from java.util.concurrent.ThreadPoolExecutor@394ac3b8[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 143]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)

**Comment by gehel** [comment]
Any chance you could send a few thread dumps to help diagnose the issue? I know we have some bugs in the way connection pools are handled, so this is probably related... just want to make sure...

**Comment by vfork001** [comment]
[jmxtrans.txt](https://github.com/jmxtrans/jmxtrans/files/210523/jmxtrans.txt)

**Comment by vfork001** [comment]
this is using OutWriterOpenTSDB
also, same config when i switched to OutputWriterOpenTSDBFactory, it can't parse config file.

**Comment by gehel** [comment]
Could you also send the config file(s)? This seems to be a different issue...

**Comment by gehel** [comment]
This *should* be fixed by #444 which will be merged shortly and available as SNAPSHOT. Feel free to re-open if that not the case.

**Comment by vfork001** [comment]
still not working, same error
[11 Apr 2016 09:02:07] [jmxtrans-result-5] 72612  WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=AvailableProcessors, className=com.
....

**Comment by dwo** [comment]
FWIW: we had the same issue on 254, so upgraded to 259. This solved the issue, but only when we used the deprecated `OpenTSDBWriter` instead of `OpenTSDBWriterFactory`.
